### PR TITLE
Fix Markdown Editor Issues

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/markdown-translatable/32)

### CODE REVIEW

**Comment by ancientTexts-net** [comment]
___
*[src/components/block-editable/README.md, line 41 at r1](https://reviewable.io/reviews/unfoldingword/markdown-translatable/32#-MK-UI-GDF64ER56u_ut:-MK-UI-GDF64ER56u_uu:b-a544ho) ([raw file](https://github.com/unfoldingword/markdown-translatable/blob/4566c72eee059a9a2315acee3cb55d3190a383b7/src/components/block-editable/README.md#L41)):*
> ```Markdown
> ```
> 
> ### Detect Hebrew and Zoom
> ```

Can you please put the demo back?
Or did it move somewhere else please?

**Review by ancientTexts-net — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/markdown-translatable/32)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

**Review by RoyalSix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/markdown-translatable/32)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ancientTexts-net)

___
*[src/components/block-editable/README.md, line 41 at r1](https://reviewable.io/reviews/unfoldingword/markdown-translatable/32#-MK-UI-GDF64ER56u_ut:-MK6I7S_57O_QuIcuHKt:bigbaq3) ([raw file](https://github.com/unfoldingword/markdown-translatable/blob/4566c72eee059a9a2315acee3cb55d3190a383b7/src/components/block-editable/README.md#L41)):*
<details><summary><i>Previously, ancientTexts-net (Zach Pennington) wrote…</i></summary><blockquote>

Can you please put the demo back?
Or did it move somewhere else please?
</blockquote></details>

Yes! My mistake

**Review by RoyalSix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/markdown-translatable/32)* status: all files reviewed, 1 unresolved discussion (waiting on @ancientTexts-net)

___
*[src/components/block-editable/README.md, line 41 at r1](https://reviewable.io/reviews/unfoldingword/markdown-translatable/32#-MK-UI-GDF64ER56u_ut:-MK6Ih0Y7LO4khk5GvXG:b-896fix) ([raw file](https://github.com/unfoldingword/markdown-translatable/blob/4566c72eee059a9a2315acee3cb55d3190a383b7/src/components/block-editable/README.md#L41)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Yes! My mistake
</blockquote></details>

Done.

**Comment by ancientTexts-net** [comment]
I experience a problem editing TSV.

markdown works fine.  TSV resets cursor to the bottom.  
- open TSV file (3 Jn)
- click in an editable block
- start typing  (NOTE: cursor resets to end of block after 1st character)

in this screenshot, I tried to type "testingasdf" but the "esting" got sent to the end of the block

**Comment by RoyalSix** [comment]
@ancientTexts-net I should checked out the branches locally, looks like you don't have the updated `markdwon-translatable` installed in the `datatable-translatable` code base

**Comment by ancientTexts-net** [comment]
yalc into datatable-translatable:


yalc into app:


from this branch:

**Comment by ancientTexts-net** [comment]
resolved.  Issue was with importing RCLs

**Pull request merged**
