### PR TITLE
Added fontSize prop to handle dynamic  font size changes to the markdown content

### PR DESCRIPTION
**Pull request by mannycolon**
# Test Instructions

- [ ] Open https://deploy-preview-57--markdown-translatable.netlify.app/#/Block%20Editable?id=blockeditable
- [ ] Scroll down to `VIEW CODE`
- [ ] Change the fontSize prop and it should change the text size above.

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/markdown-translatable/57)

### CODE REVIEW

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/markdown-translatable/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

**Comment by PhotoNomad0** [comment]
LGTM

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/markdown-translatable/57)* status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/components/block-editable/BlockEditable.js, line 143 at r1](https://reviewable.io/reviews/unfoldingword/markdown-translatable/57#-MZK86F8Ex1T_xD0JIBU:-MZK86F8Ex1T_xD0JIBV:b-mkd926) ([raw file](https://github.com/unfoldingword/markdown-translatable/blob/2116ef77f8b4165b063e9b56b59f7da3670fefd5/src/components/block-editable/BlockEditable.js#L143)):*
> ```JavaScript
>   editable: PropTypes.bool,
>   /** fontSize for Markdown class, e.g. '100%' */
>   fontSize: PropTypes.string,
> ```

I don't see where fontSize prop is used in BlockEditable

**Comment by mannycolon** [comment]
It is used in the makeStyles that generates the classes used in the component

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/markdown-translatable/57)* status: all files reviewed, 2 unresolved discussions (waiting on @mannycolon)

___
*[src/components/block-editable/BlockEditable.js, line 25 at r1](https://reviewable.io/reviews/unfoldingword/markdown-translatable/57#-MZK8l6L7QbhVPGXqDHw:-MZK8l6L7QbhVPGXqDHx:b-haj12c) ([raw file](https://github.com/unfoldingword/markdown-translatable/blob/2116ef77f8b4165b063e9b56b59f7da3670fefd5/src/components/block-editable/BlockEditable.js#L25)):*
> ```JavaScript
>   style,
>   preview,
>   editable,
> ```

Shouldn't fontSize prop be here?

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/markdown-translatable/57)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/markdown-translatable/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

**Pull request merged**
